import "./globals.css";

import type { Metadata } from "next";
import { Inter, Lexend } from "next/font/google";

import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const fontSans = Lexend({
  variable: "--font-sans",
  subsets: ["latin"],
});

const fontHeading = Lexend({
  variable: "--font-heading",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PIEMONTECNICA - LEVELS OG",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen font-sans antialiased flex flex-col",
          fontSans.variable,
          fontHeading.variable
        )}
      >
        <Navbar />
        <main className="flex-grow pt-20">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
